FRAMAC_SHARE := $(shell frama-c-config -print-share-path)
FRAMAC_LIBDIR := $(shell frama-c-config -print-libpath)
PLUGIN_NAME = Hello
PLUGIN_CMO = hello_world
PLUGIN_REQUIRES = uberspark
include $(FRAMAC_SHARE)/Makefile.dynamic