######
# Makefile for UberSpark tools (libs)
# author: amit vasudevan (amitvasudevan@acm.org)
######

include ../../uberspark-common.mk


###### targets

.PHONY: all
all: 
	cd libuslog && $(MAKE) -w all
	cd libusmf && $(MAKE) -w all
	

.PHONY: clean
clean:
	cd libuslog && $(MAKE) -w clean
	cd libusmf && $(MAKE) -w clean
	
	
