#   hello_mul Makefile
#
#   minimal coss example application that multiplies two unsigned 32-bit integers 
#   specified via integer parameters and returns the result
#   
#    author: amit vasudevan <amitvasudevan@acm.org>
#

###### targets

.PHONY: all
all: 
	@echo building hello_mul...
	gcc -m32 -o hello_mul main.c
	@echo built hello_mul successfully!


.PHONY: clean
clean: 
	rm -f *.o
	rm -f hello_mul
