
/* autogenerated XMHF/GEEC sentinel slab info table */
/* author: amit vasudevan (amitvasudevan@acm.org) */


#include <xmhf.h>
#include <xmhfgeec.h>
#include <xmhf-debug.h>


__attribute__(( section(".data") )) __attribute__((aligned(4096))) xmhfgeec_slab_info_t xmhfgeec_slab_info_table[] = {

	//geec_sentinel
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_SENTINEL,
        0x04200000  + (2 * 4096),
        0x00000000UL,
	        {
	            0x03800000 + (1*XMHF_SLAB_STACKSIZE),
	            0x03800000 + (2*XMHF_SLAB_STACKSIZE),
	            0x03800000 + (3*XMHF_SLAB_STACKSIZE),
	            0x03800000 + (4*XMHF_SLAB_STACKSIZE),
	            0x03800000 + (5*XMHF_SLAB_STACKSIZE),
	            0x03800000 + (6*XMHF_SLAB_STACKSIZE),
	            0x03800000 + (7*XMHF_SLAB_STACKSIZE),
	            0x03800000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000106UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
	{ .vendor_id= 0xFFFF, .device_id= 0x0000 },
}, 

0x00000001,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x03200000, .addr_end = 0x03400000, .protection = 0},
	        {.addr_start = 0x03400000, .addr_end = 0x03800000, .protection = 0},
	        {.addr_start = 0x03800000, .addr_end = 0x03e00000, .protection = 0},
	        {.addr_start = 0x03e00000, .addr_end = 0x04000000, .protection = 0},
	    },
	    {0
	    },
	    0x03200000
	},


	//geec_prime
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
        0x04200000  + (2 * 4096),
        0x00000000UL,
	        {
	            0x07a00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x07a00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x07a00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x07a00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x07a00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x07a00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x07a00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x07a00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000000UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000003,
	0x00000002,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
	{ .vendor_id= 0xFFFF, .device_id= 0x0000 },
	{ .vendor_id= 0xFFFF, .device_id= 0x0002 },
	{ .vendor_id= 0xFFFF, .device_id= 0x0001 },
	{ .vendor_id= 0xFFFF, .device_id= 0x0003 },
}, 

0x00000004,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x04000000, .addr_end = 0x04200000, .protection = 0},
	        {.addr_start = 0x04200000, .addr_end = 0x07a00000, .protection = 0},
	        {.addr_start = 0x07a00000, .addr_end = 0x08800000, .protection = 0},
	        {.addr_start = 0x08800000, .addr_end = 0x08a00000, .protection = 0},
	    },
	    {0
	    },
	    0x04000000
	},


	//xc_init
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
        0x04200000  + (2 * 4096),
        0x00000000UL,
	        {
	            0x08e00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x08e00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x08e00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x08e00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x08e00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x08e00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x08e00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x08e00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000002UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x0000000b,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x08a00000, .addr_end = 0x08c00000, .protection = 0},
	        {.addr_start = 0x08c00000, .addr_end = 0x08e00000, .protection = 0},
	        {.addr_start = 0x08e00000, .addr_end = 0x09400000, .protection = 0},
	        {.addr_start = 0x09400000, .addr_end = 0x09600000, .protection = 0},
	    },
	    {0
	    },
	    0x08a00000
	},


	//xc_exhub
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
        0x04200000  + (2 * 4096),
        0x00000000UL,
	        {
	            0x09a00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x09a00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x09a00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x09a00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x09a00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x09a00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x09a00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x09a00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000010UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x09600000, .addr_end = 0x09800000, .protection = 0},
	        {.addr_start = 0x09800000, .addr_end = 0x09a00000, .protection = 0},
	        {.addr_start = 0x09a00000, .addr_end = 0x0a000000, .protection = 0},
	        {.addr_start = 0x0a000000, .addr_end = 0x0a200000, .protection = 0},
	    },
	    {0
	    },
	    0x09600000
	},


	//xc_ihub
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
        0x04200000  + (2 * 4096),
        0x00000000UL,
	        {
	            0x0a600000 + (1*XMHF_SLAB_STACKSIZE),
	            0x0a600000 + (2*XMHF_SLAB_STACKSIZE),
	            0x0a600000 + (3*XMHF_SLAB_STACKSIZE),
	            0x0a600000 + (4*XMHF_SLAB_STACKSIZE),
	            0x0a600000 + (5*XMHF_SLAB_STACKSIZE),
	            0x0a600000 + (6*XMHF_SLAB_STACKSIZE),
	            0x0a600000 + (7*XMHF_SLAB_STACKSIZE),
	            0x0a600000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000000UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x0000000f,
	0x00000003,
	0x00000008,
	0x0000000c,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x0a200000, .addr_end = 0x0a400000, .protection = 0},
	        {.addr_start = 0x0a400000, .addr_end = 0x0a600000, .protection = 0},
	        {.addr_start = 0x0a600000, .addr_end = 0x0ac00000, .protection = 0},
	        {.addr_start = 0x0ac00000, .addr_end = 0x0ae00000, .protection = 0},
	    },
	    {0
	    },
	    0x0a200000
	},


	//xc_nwlog
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
        0x04200000  + (2 * 4096),
        0x00000000UL,
	        {
	            0x0b200000 + (1*XMHF_SLAB_STACKSIZE),
	            0x0b200000 + (2*XMHF_SLAB_STACKSIZE),
	            0x0b200000 + (3*XMHF_SLAB_STACKSIZE),
	            0x0b200000 + (4*XMHF_SLAB_STACKSIZE),
	            0x0b200000 + (5*XMHF_SLAB_STACKSIZE),
	            0x0b200000 + (6*XMHF_SLAB_STACKSIZE),
	            0x0b200000 + (7*XMHF_SLAB_STACKSIZE),
	            0x0b200000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000400UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
	{ .vendor_id= 0x8086, .device_id= 0x10b9 },
}, 

0x00000001,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x0ae00000, .addr_end = 0x0b000000, .protection = 0},
	        {.addr_start = 0x0b000000, .addr_end = 0x0b200000, .protection = 0},
	        {.addr_start = 0x0b200000, .addr_end = 0x0b800000, .protection = 0},
	        {.addr_start = 0x0b800000, .addr_end = 0x0ba00000, .protection = 0},
	    },
	    {0
	    },
	    0x0ae00000
	},


	//uapi_gcpustate
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
        0x04200000  + (2 * 4096),
        0x00000000UL,
	        {
	            0x0be00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x0be00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x0be00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x0be00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x0be00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x0be00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x0be00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x0be00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00001c14UL, 
       true,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x0ba00000, .addr_end = 0x0bc00000, .protection = 0},
	        {.addr_start = 0x0bc00000, .addr_end = 0x0be00000, .protection = 0},
	        {.addr_start = 0x0be00000, .addr_end = 0x0c400000, .protection = 0},
	        {.addr_start = 0x0c400000, .addr_end = 0x0c600000, .protection = 0},
	    },
	    {0
	    },
	    0x0ba00000
	},


	//uapi_hcpustate
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
        0x04200000  + (2 * 4096),
        0x00000000UL,
	        {
	            0x0ca00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x0ca00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x0ca00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x0ca00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x0ca00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x0ca00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x0ca00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x0ca00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000010UL, 
       true,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x0c600000, .addr_end = 0x0c800000, .protection = 0},
	        {.addr_start = 0x0c800000, .addr_end = 0x0ca00000, .protection = 0},
	        {.addr_start = 0x0ca00000, .addr_end = 0x0d000000, .protection = 0},
	        {.addr_start = 0x0d000000, .addr_end = 0x0d200000, .protection = 0},
	    },
	    {0
	    },
	    0x0c600000
	},


	//uapi_slabmempgtbl
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
        0x04200000  + (2 * 4096),
        0x00000000UL,
	        {
	            0x11600000 + (1*XMHF_SLAB_STACKSIZE),
	            0x11600000 + (2*XMHF_SLAB_STACKSIZE),
	            0x11600000 + (3*XMHF_SLAB_STACKSIZE),
	            0x11600000 + (4*XMHF_SLAB_STACKSIZE),
	            0x11600000 + (5*XMHF_SLAB_STACKSIZE),
	            0x11600000 + (6*XMHF_SLAB_STACKSIZE),
	            0x11600000 + (7*XMHF_SLAB_STACKSIZE),
	            0x11600000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000c12UL, 
       true,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x0d200000, .addr_end = 0x0d400000, .protection = 0},
	        {.addr_start = 0x0d400000, .addr_end = 0x11600000, .protection = 0},
	        {.addr_start = 0x11600000, .addr_end = 0x11c00000, .protection = 0},
	        {.addr_start = 0x11c00000, .addr_end = 0x11e00000, .protection = 0},
	    },
	    {0
	    },
	    0x0d200000
	},


	//uapi_sysdata
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
        0x04200000  + (2 * 4096),
        0x00000000UL,
	        {
	            0x12200000 + (1*XMHF_SLAB_STACKSIZE),
	            0x12200000 + (2*XMHF_SLAB_STACKSIZE),
	            0x12200000 + (3*XMHF_SLAB_STACKSIZE),
	            0x12200000 + (4*XMHF_SLAB_STACKSIZE),
	            0x12200000 + (5*XMHF_SLAB_STACKSIZE),
	            0x12200000 + (6*XMHF_SLAB_STACKSIZE),
	            0x12200000 + (7*XMHF_SLAB_STACKSIZE),
	            0x12200000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000012UL, 
       true,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x11e00000, .addr_end = 0x12000000, .protection = 0},
	        {.addr_start = 0x12000000, .addr_end = 0x12200000, .protection = 0},
	        {.addr_start = 0x12200000, .addr_end = 0x12800000, .protection = 0},
	        {.addr_start = 0x12800000, .addr_end = 0x12a00000, .protection = 0},
	    },
	    {0
	    },
	    0x11e00000
	},


	//xh_syscalllog
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
        0x04200000  + (2 * 4096),
        0x00000000UL,
	        {
	            0x12e00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x12e00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x12e00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x12e00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x12e00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x12e00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x12e00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x12e00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000014UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000003,
	0x0000000f,
	0x00000000,
	0x0000000e,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x12a00000, .addr_end = 0x12c00000, .protection = 0},
	        {.addr_start = 0x12c00000, .addr_end = 0x12e00000, .protection = 0},
	        {.addr_start = 0x12e00000, .addr_end = 0x13400000, .protection = 0},
	        {.addr_start = 0x13400000, .addr_end = 0x13600000, .protection = 0},
	    },
	    {0
	    },
	    0x12a00000
	},


	//xh_hyperdep
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
        0x04200000  + (2 * 4096),
        0x00000000UL,
	        {
	            0x13a00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x13a00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x13a00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x13a00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x13a00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x13a00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x13a00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x13a00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000014UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000005,
	0x00000000,
	0x00000006,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x13600000, .addr_end = 0x13800000, .protection = 0},
	        {.addr_start = 0x13800000, .addr_end = 0x13a00000, .protection = 0},
	        {.addr_start = 0x13a00000, .addr_end = 0x14000000, .protection = 0},
	        {.addr_start = 0x14000000, .addr_end = 0x14200000, .protection = 0},
	    },
	    {0
	    },
	    0x13600000
	},


	//xh_ssteptrace
	{
	    true,
	        XMHFGEEC_SLABTYPE_uVU_PROG,
        0x04200000 + (3*4096) + (0 * 4096),
        0x04200000 + (3*4096) + (1 *4096) + (0 * (3*4096)), 
	        {
	            0x14600000 + (1*XMHF_SLAB_STACKSIZE),
	            0x14600000 + (2*XMHF_SLAB_STACKSIZE),
	            0x14600000 + (3*XMHF_SLAB_STACKSIZE),
	            0x14600000 + (4*XMHF_SLAB_STACKSIZE),
	            0x14600000 + (5*XMHF_SLAB_STACKSIZE),
	            0x14600000 + (6*XMHF_SLAB_STACKSIZE),
	            0x14600000 + (7*XMHF_SLAB_STACKSIZE),
	            0x14600000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000014UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000007,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x14200000, .addr_end = 0x14400000, .protection = 0},
	        {.addr_start = 0x14400000, .addr_end = 0x14600000, .protection = 0},
	        {.addr_start = 0x14600000, .addr_end = 0x14c00000, .protection = 0},
	        {.addr_start = 0x14c00000, .addr_end = 0x14e00000, .protection = 0},
	    },
	    {0
	    },
	    0x14200000
	},


	//xg_richguest
	{
	    true,
	        XMHFGEEC_SLABTYPE_uVU_PROG_RICHGUEST,
        0x0d400000  + (0 * 4096),
        0x04200000  + (3*4096) + (1 * 4096) + (1 *(3*4096)) + (0 * (3*4096)),
	        {
	            0x00000000 + (1*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (2*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (3*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (4*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (5*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (6*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (7*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000004UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00001414,
       0x00001414,

{ 
	{ .vendor_id= 0xffff, .device_id= 0xffff },
}, 

0x00000001,

{ 
	{ .vendor_id= 0x8086, .device_id= 0x10b9 },
}, 

0x00000001,
	    {
	        {.addr_start = 0x00000000, .addr_end = 0x03200000, .protection = 0},
	        {.addr_start = 0x1f400000, .addr_end = 0xffffffff, .protection = 0},
	        {.addr_start = 0x00000000, .addr_end = 0x00000000, .protection = 0},
	        {.addr_start = 0x00000000, .addr_end = 0x00000000, .protection = 0},
	    },
	    {0
	    },
	    0x00000000
	},

};