(*
	uberSpark configuration module
	author: amit vasudevan (amitvasudevan@acm.org)
*)
open Unix
open Yojson

(*------------------------------------------------------------------------*)
(* header related configuration settings *)	
(*------------------------------------------------------------------------*)
let hdr_type = ref "";;
let hdr_namespace = ref "";;
let hdr_platform = ref "";;
let hdr_arch = ref "";;
let hdr_cpu = ref "";;


(*------------------------------------------------------------------------*)
(* environment related configuration settings *)	
(*------------------------------------------------------------------------*)
(*let env_path_seperator = ref "/";;*)
let env_home_dir = ref "HOME";;


(*------------------------------------------------------------------------*)
(* namespace related configuration settings *)	
(*------------------------------------------------------------------------*)
let namespace_root = ((Unix.getenv !env_home_dir) ^ "/");;
let namespace_default_uobj_mf_filename = "uberspark-uobj-mf.json";;
let namespace_uobj_mf_hdr_type = "uobj";;

let namespace_uobj_binhdr_src_filename = "uobj_binhdr.c";;
let namespace_uobj_publicmethods_info_src_filename = "uobj_pminfo.c";;
let namespace_uobj_intrauobjcoll_callees_info_src_filename = "uobj_intrauobjcoll_callees_info.c";;
let namespace_uobj_interuobjcoll_callees_info_src_filename = "uobj_interuobjcoll_callees_info.c";;
let namespace_uobj_linkerscript_filename = "uobj.lscript";;

let namespace_uobjslt = (namespace_root ^ "uberspark/uobjslt");;
let namespace_uobjslt_mf_hdr_type = "uobjslt";;
let namespace_uobjslt_mf_filename = "uberspark-uobjslt-mf.json";;
let namespace_uobjslt_callees_output_filename = "uobjslt-callees.S";;
let namespace_uobjslt_exitcallees_output_filename = "uobjslt-exitcallees.S";;
let namespace_uobjslt_output_symbols_filename = "uobjslt-symbols.json";;


(*------------------------------------------------------------------------*)
(* uobj/uobjcoll binary related configuration settings *)	
(*------------------------------------------------------------------------*)
let binary_page_size = ref 0x00200000;;
let binary_uobj_section_alignment = ref 0x00200000;;
let binary_uobj_default_section_size = ref 0x00200000;;

let binary_uobj_default_load_addr = ref 0x60000000;;
let binary_uobj_default_size = ref 0x01000000;;



let switch 
	(config_ns : string)
	: bool =
	let retval = ref false in
	let config_ns_json_path = namespace_root ^ config_ns ^ "/uberspark-config.json" in
	Uberspark_logger.log "config_ns_json_path=%s" config_ns_json_path;

	try
		let config_json = Yojson.Basic.from_file config_ns_json_path in
		(*parse header*)
		let config_json_hdr = Yojson.Basic.Util.member "hdr" config_json in
			hdr_type := Yojson.Basic.Util.to_string (Yojson.Basic.Util.member "type" config_json_hdr);
			hdr_namespace := Yojson.Basic.Util.to_string (Yojson.Basic.Util.member "namespace" config_json_hdr);
			hdr_platform := Yojson.Basic.Util.to_string (Yojson.Basic.Util.member "platform" config_json_hdr);
			hdr_arch := Yojson.Basic.Util.to_string (Yojson.Basic.Util.member "arch" config_json_hdr);
			hdr_cpu := Yojson.Basic.Util.to_string (Yojson.Basic.Util.member "cpu" config_json_hdr);
			(* TBD: sanity check header *)
		
		let config_json_settings = 	Yojson.Basic.Util.member "settings" config_json in

			binary_page_size := int_of_string (Yojson.Basic.Util.to_string (Yojson.Basic.Util.member "binary_page_size" config_json_settings));
			binary_uobj_section_alignment := int_of_string (Yojson.Basic.Util.to_string (Yojson.Basic.Util.member "binary_uobj_section_alignment" config_json_settings));
			binary_uobj_default_section_size := int_of_string (Yojson.Basic.Util.to_string (Yojson.Basic.Util.member "binary_uobj_default_section_size" config_json_settings));
			binary_uobj_default_load_addr := int_of_string (Yojson.Basic.Util.to_string (Yojson.Basic.Util.member "binary_uobj_default_load_addr" config_json_settings));
			binary_uobj_default_size := int_of_string (Yojson.Basic.Util.to_string (Yojson.Basic.Util.member "binary_uobj_default_size" config_json_settings));


		retval := true;							
	with Yojson.Json_error s -> 
		Uberspark_logger.log ~lvl:Uberspark_logger.Error "%s" s;
		retval := false;
	;
					


	(!retval)
;;


let dump 
	(output_config_filename : string)
	=

	let oc = open_out output_config_filename in
		Printf.fprintf oc "\n/* --- this file is autogenerated --- */";
		Printf.fprintf oc "\n/* uberSpark configuration file */";
		Printf.fprintf oc "\n";
		Printf.fprintf oc "\n";
		Printf.fprintf oc "\n{";
		Printf.fprintf oc "\n\t\"hdr\":{";
		Printf.fprintf oc "\n\t\t\"type\" : \"%s\"," !hdr_type;
		Printf.fprintf oc "\n\t\t\"namespace\" : \"%s\"," !hdr_namespace;
		Printf.fprintf oc "\n\t\t\"platform\" : \"%s\"," !hdr_platform;
		Printf.fprintf oc "\n\t\t\"arch\" : \"%s\"," !hdr_arch;
		Printf.fprintf oc "\n\t\t\"cpu\" : \"%s\"" !hdr_cpu;
		Printf.fprintf oc "\n\t},";
		Printf.fprintf oc "\n";
		Printf.fprintf oc "\n\t\"settings\":{";
		Printf.fprintf oc "\n\t\t\"binary_page_size\" : \"0x%x\"," !binary_page_size;
		Printf.fprintf oc "\n\t\t\"binary_uobj_section_alignment\" : \"0x%x\"," !binary_uobj_section_alignment;
		Printf.fprintf oc "\n\t\t\"binary_uobj_default_section_size\" : \"0x%x\"," !binary_uobj_default_section_size;
		Printf.fprintf oc "\n\t\t\"binary_uobj_default_load_addr\" : \"0x%x\"," !binary_uobj_default_load_addr;
		Printf.fprintf oc "\n\t\t\"binary_uobj_default_size\" : \"0x%x\"" !binary_uobj_default_size;
		Printf.fprintf oc "\n\t}";
		Printf.fprintf oc "\n";
		Printf.fprintf oc "\n}";
	close_out oc;	


;;


let settings_set 
	(setting_name : string)
	(setting_value : string)
	: bool =

	let retval = ref true in
	match setting_name with
		| "binary_page_size" -> binary_page_size := int_of_string setting_value;
		| "binary_uobj_section_alignment" -> binary_uobj_section_alignment := int_of_string setting_value;
		| "binary_uobj_default_section_size" -> binary_uobj_default_section_size := int_of_string setting_value;
		| "binary_uobj_default_load_addr" -> binary_uobj_default_load_addr := int_of_string setting_value;
		| "binary_uobj_default_size" -> binary_uobj_default_size := int_of_string setting_value;
		| _ -> retval := false;
	;
	
	!retval
;;


let settings_get 
	(setting_name : string)
	: (bool * string) =

	let retstatus = ref true in
	let settings_value = ref "" in
	match setting_name with
		| "binary_page_size" -> settings_value := (Printf.sprintf "0x%x" !binary_page_size);
		| "binary_uobj_section_alignment" -> settings_value := (Printf.sprintf "0x%x" !binary_uobj_section_alignment);
		| "binary_uobj_default_section_size" -> settings_value := (Printf.sprintf "0x%x" !binary_uobj_default_section_size);
		| "binary_uobj_default_load_addr" -> settings_value := (Printf.sprintf "0x%x"  !binary_uobj_default_load_addr);
		| "binary_uobj_default_size" -> settings_value := (Printf.sprintf "0x%x" !binary_uobj_default_size);
		| _ -> retstatus := false;
	;
	
	(!retstatus, !settings_value)
;;


let create_from_existing_ns
	(input_config_ns : string)
	(output_config_ns : string)
	: (bool * string) =
	let retval = ref false in
	let reterrmsg = ref "" in

	let output_config_dir = (namespace_root ^ output_config_ns) in
	let output_config_json_pathname = output_config_dir ^ "/uberspark-config.json" in

	(* switch to the input config ns *)
	switch input_config_ns;

	(* change namespace field *)
	hdr_namespace := output_config_ns;

	(* make the output config directory *)
	let (rval, recode, remsg) = Uberspark_osservices.mkdir output_config_dir 0o777 in
	if(rval == true) then 
		begin
			retval := true;
			reterrmsg := "";
			(* dump the config namespace *)
			dump output_config_json_pathname;
		end
	else
		reterrmsg := remsg;
	;

	(!retval, !reterrmsg)
;;


let create_from_file
	(input_config_json_pathname : string)
	(output_config_ns : string)
	: (bool * string) =
	let retval = ref false in
	let reterrmsg = ref "" in

	let output_config_dir = (namespace_root ^ output_config_ns) in
	let output_config_json_pathname = output_config_dir ^ "/uberspark-config.json" in

	let (rval, recode, remsg) = Uberspark_osservices.mkdir output_config_dir 0o777 in
	if(rval == true) then 
		begin
			retval := true;
			reterrmsg := "";
			Uberspark_osservices.file_copy input_config_json_pathname output_config_json_pathname;
		end
	else
		reterrmsg := remsg;
	;

	(!retval, !reterrmsg)
;;


